### ISSUE TITLE
Get percentage of the whole scratch area

### ISSUE THREAD

**Issue by liauli** [sharish/ScratchView#10]
Hi and thank you for this library, it's very helpful!
But I have a question, can we get the percentage or check if the whole scratch area is revealed? as for now, we only can detect the percentage of the text/image area inside the scratch view. Any help would be appreciated! Thank you very much

**Comment by gauravarora90** [comment]
Dear Liauli,

    I think you can calculate the same yourself. e.g

```
@Override
    public void onRevealPercentChangedListener(ScratchImageView siv, float percent) {
        // on image percent reveal
float scratchedOutPercentage = 100-percent;
    }
```


Hope it helps you.

**Comment by subzeroz** [comment]
Hello gauravarora90, I tried the code you posted, but it is not showing the percentage on the textview.

I am trying to make a game where the player has to scratch to reveal a picture, and I want to allow him to only scratch a certain percentage of the picture.

Here is my code:


    private float scratchedOutPercentage;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ScratchImageView scratchImageView = new ScratchImageView(this);

        final TextView percentageTV = (TextView) findViewById(R.id.scratchPercentageTV);

        scratchImageView.setRevealListener(new ScratchImageView.IRevealListener() {
            @Override
            public void onRevealed(ScratchImageView tv) {
                // on reveal
            }

            @Override
            public void onRevealPercentChangedListener(ScratchImageView siv, float percent) {
                // on image percent reveal
                scratchedOutPercentage = 100-percent;

            }
        });

        percentageTV.setText(String.valueOf(scratchedOutPercentage));
    }`

**Comment by sharish** [comment]
Hi @subzeroz ,

Change your code to put setText inside reveal listener callback. 

Something equivalent to below.

```java
private float scratchedOutPercentage;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    ScratchImageView scratchImageView = new ScratchImageView(this);

    final TextView percentageTV = (TextView) findViewById(R.id.scratchPercentageTV);

    scratchImageView.setRevealListener(new ScratchImageView.IRevealListener() {
        @Override
        public void onRevealed(ScratchImageView tv) {
            // on reveal
        }

        @Override
        public void onRevealPercentChangedListener(ScratchImageView siv, float percent) {
            // on image percent reveal
              scratchedOutPercentage = 1-percent; // Note : percent value will be between 0.0 to 1.0

            percentageTV.setText(String.valueOf(scratchedOutPercentage));

        }
    });

}
```

Thanks,
Harish

**Comment by AmineCherrai** [comment]
Hi @sharish ,  @subzeroz 

I tried your code but didn't work. I had to change 

`ScratchImageView scratchImageView = new ScratchImageView(this);`

with 

`ScratchImageView scratchImageView = findViewById(R.id.ScratchImageView);`
