### ISSUE TITLE
Get percent image discover

### ISSUE THREAD

**Issue by webserveis** [sharish/ScratchView#2]
Is it possible to get the percent of discover surface?

**Comment by cooltechworks** [comment]
Yes possible. Will add in v1.1

Thanks,
Harish

**Comment by Trunksome** [comment]
Would love that extension as well! Any updates?

**Comment by sharish** [comment]
Cool. Will work and push it soon. Wait for a day or two.

Thanks,
Harish

**Comment by sharish** [comment]
@webserveis  @Trunksome v1.1 is published and it now include percent reveal.

Thanks for your inputs. Report if you encounter any issues.

Thanks,
Harish

**Comment by Trunksome** [comment]
works like a charm, thanks! :)
Suggestion: add a .getPercentageRevealed() method to the view as well.
