### ISSUE TITLE
java.lang.IllegalArgumentException width and height must be > 0

### ISSUE THREAD

**Issue by akingyin1987** [sharish/ScratchView#3]
java.lang.IllegalArgumentExceptionwidth and height must be > 0

com.cooltechworks.views.ScratchTextView.onSizeChanged(ScratchTextView.java:160)

**Comment by cooltechworks** [comment]
This will be addressed soon.

Thanks,
Harish

**Comment by sharish** [comment]
Unable to reproduce. Re-open the issue if you have some detailed info. 

Thanks!
