### ISSUE TITLE
can not set imageresource

### ISSUE THREAD

**Issue by 123pavan123** [sharish/ScratchView#7]
can not set image resource programetically, if remove src from xml file and try to set src programetically using "scratchimageview.setimageresource" it displays nothing

**Comment by kenyz0r** [comment]
It will work if you instantiate ScratchImageView by using findViewById. Please take a look at the snippet below:
ScratchImageView scratchImageView = (ScratchImageView) findViewById(R.id.sample_image);
                Resources resources = getResources();
                final int resourceID = resources.getIdentifier(b.getString("promoCode"), "drawable", getPackageName());
                scratchImageView.setImageDrawable(resources.getDrawable(resourceID, null));
